
package domainapp.dom.modules.servicios;

public enum E_estado {
	SIN_REVISAR,EN_REVISIÓN,A_PRESUPUESTAR,PRESUPUESTADO,
	FALTAN_REPUESTOS,ANULADO,LISTO_PARA_REPARAR,PRES_RECHAZADO,
	A_PRUEBA,TERMINADO,NO_SE_REPARA,CLIENTE_AVISADO,ABANDONADO,
	REPARADO,ENTREGADO,ENESPERA;

}
